stages:
  - test
  - build

before_script:
  - rm /usr/local/bin/yarn && rm /usr/local/bin/yarnpkg
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - mkdir .yarn_cache && yarn config set cache-folder .yarn_cache

.job_template: &job_definition
  stage: test
  retry: 2
  only:
    variables:
      - $NIGHTLY_BUILD
  cache:
    key: '$CI_BUILD_NAME'
    paths:
      - .yarn_cache/
  script:
    - yarn --non-interactive --frozen-lockfile
    # - yarn audit
    - yarn lint
    - yarn test
    - yarn coverage

Node 8:
  <<: *job_definition
  image: node:8

Node 10:
  <<: *job_definition
  image: node:10

Node 12:
  <<: *job_definition
  image: node:12

Publish nightly build:
  stage: build
  image: node:10
  only:
    variables:
      - $NIGHTLY_BUILD
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - yarn --non-interactive --frozen-lockfile
    - yarn lerna publish -c patch --no-git-tag-version --no-push --npm-tag nightly --yes --force-publish --npm-client npm --preid nightly.$(date +%Y%m%d%H%M%S) --registry https://registry.npmjs.org
